### ISSUE TITLE
Ie7 issue

### ISSUE THREAD

**Issue by edankwan** [tbranyen/lodash-template-loader#12]
IE7 fails on this as it doesn't support array-like access
```js
if (settings.root && settings.root[settings.root.length-1] !== "/") {
    settings.root += "/";
}
```

Use this will work
```
if (settings.root && settings.root.substr(settings.root.length-1) !== "/") {
...
```

I know... who cares about IE7 lol

**Comment by tbranyen** [comment]
That's a good point, I should have used slice/substring instead.  I think `substr` is nonstandard (unless my memory is failing me).
