### ISSUE TITLE
Minifying / removing spaces in html

### ISSUE THREAD

**Issue by dharapvj** [tbranyen/lodash-template-loader#14]
Currently.. the template content is not zapped to remove tabs, spaces etc...
See [here](http://stackoverflow.com/a/18790972) about how we can quickly remove that in the content by adding a regex.

Can you consider this enhancement?
mostly we need to make this change after [this line](https://github.com/tbranyen/lodash-template-loader/blob/1.0.0/loader.js#L58).

**Comment by tbranyen** [comment]
That makes sense for browsers, but that would be really annoying if some was using this for say, source code generation.

**Comment by tbranyen** [comment]
Gonna punt on this, because you can always gzip the file after bundling.

**Comment by tbranyen** [comment]
Thanks for bringing up this issue though! Don't take the close to mean it's a bad idea, I just don't think it's ideal for the various use cases lodash-template-loader is for.

**Comment by dharapvj** [comment]
Fair enough Tim.

Thanks for elaborating your thoughts.
