### ISSUE TITLE
root setting can't be overridden with require.config

### ISSUE THREAD

**Issue by absolux** [tbranyen/lodash-template-loader#16]
I can't override the templates root directory via
```js
require.config({
  ...
  lodashLoader: {
    root: "./templates/",
  }
  ...
});
```
in the configure function, `config.lodashLoader` is undefined.

**Comment by absolux** [comment]
lodashLoader is reachable with `config.config.lodashLoader` not `config.lodashLoader`

**Comment by tbranyen** [comment]
Check out our unit test for this, works fine with `require.config` without having to namespace:

https://github.com/tbranyen/lodash-template-loader/blob/master/test/spec/requirejs.js#L84-L94

Am I missing something?

**Comment by absolux** [comment]
After investigation, i was using `lodashLoader` attribute inside another config attribute, for that reason `config.lodashLoader` was unreachable. 

I close this issue as resolved. Thanks for your reply
